/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _BOARD_SM3_MU_H_
#define _BOARD_SM3_MU_H_ 

#include <arch/cm3/nxp/vendor/fsl_common.h>
#include <arch/cm3/nxp/vendor/fsl_port.h>
#include <arch/cm3/nxp/vendor/fsl_sysmpu.h>
#include <arch/cm3/nxp/vendor/fsl_gpio.h>
#include <arch/cm3/nxp/vendor/fsl_flexbus.h>

#ifndef DEV_ETHER
#include <dev/eth_mcux.h>
#define DEV_ETHER devEthMcux
#endif


#ifndef DEV_UART0
#include <arch/cm3/nxp/mk64f_usart.h>
#define DEV_UART0 devMk64fUsart_0
#define NUTUART0 DEV_UART0
#endif


#ifndef DEV_UART1
#include <arch/cm3/nxp/mk64f_usart.h>
#define DEV_UART1 devMk64fUsart_1
#define NUTUART1 DEV_UART1
#endif

#ifndef DEV_UART2
#include <arch/cm3/nxp/mk64f_usart.h>
#define DEV_UART2 devMk64fUsart_2
#define NUTUART2 DEV_UART2
#endif


#ifndef RTC_CHIP
#include <dev/mk64f_rtc.h>
#define RTC_CHIP rtcMk64f
#endif

#define BOARD_SDHC_BASEADDR SDHC
#define BOARD_SDHC_CLK_FREQ CLOCK_GetFreq(kCLOCK_CoreSysClk)
#define BOARD_SDHC_CD_GPIO_BASE GPIOC
#define BOARD_SDHC_CD_GPIO_PIN 3U


typedef void (*TMWDTResetFN)(void);
/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif


#define BOARD_USART0_RE1_GPIO GPIOB
#define BOARD_USART0_RE1_PIN 4
#define BOARD_USART0_DE1_GPIO GPIOB
#define BOARD_USART0_DE1_PIN 5
#define BOARD_USART0_RE2_GPIO GPIOC
#define BOARD_USART0_RE2_PIN 18
#define BOARD_USART0_DE2_GPIO GPIOC
#define BOARD_USART0_DE2_PIN 19

#define BOARD_USART4_RE1_GPIO GPIOE
#define BOARD_USART4_RE1_PIN 6
#define BOARD_USART4_DE1_GPIO GPIOE
#define BOARD_USART4_DE1_PIN 7

#define BOARD_USART5_DTR_GPIO GPIOE
#define BOARD_USART5_DTR_PIN 26
#define BOARD_USART5_RI_GPIO GPIOE
#define BOARD_USART5_RI_PIN 27
#define BOARD_USART5_RTS_GPIO GPIOE
#define BOARD_USART5_RTS_PIN 11
#define BOARD_USART5_CTS_GPIO GPIOE
#define BOARD_USART5_CTS_PIN 10

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTE28 (number 49), 232_STATUS
  @{ */
#define BOARD_INITPINS_RS232_STATUS_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_RS232_STATUS_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_RS232_STATUS_PIN 28U    /*!<@brief PORTE pin index: 28 */
                                               /* @} */

/*! @name PORTE27 (number 48), 232_RI
  @{ */
#define BOARD_INITPINS_RS232_RI_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_RS232_RI_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_RS232_RI_PIN 27U    /*!<@brief PORTE pin index: 27 */
                                           /* @} */

/*! @name PORTE26 (number 47), 232_DTR
  @{ */
#define BOARD_INITPINS_RS232_DTR_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_RS232_DTR_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_RS232_DTR_PIN 26U    /*!<@brief PORTE pin index: 26 */
                                            /* @} */

/*! @name PORTE12 (number 15), 232_SHTDWN
  @{ */
#define BOARD_INITPINS_RS232_SHTDWN_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_RS232_SHTDWN_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_RS232_SHTDWN_PIN 12U    /*!<@brief PORTE pin index: 12 */
                                               /* @} */

/*! @name PORTE6 (number 9), 485_RE
  @{ */
#define BOARD_INITPINS_RS485_RE_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_RS485_RE_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_RS485_RE_PIN 6U     /*!<@brief PORTE pin index: 6 */
                                           /* @} */

/*! @name PORTE7 (number 10), 485_DE
  @{ */
#define BOARD_INITPINS_RS485_DE_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_RS485_DE_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_RS485_DE_PIN 7U     /*!<@brief PORTE pin index: 7 */
                                           /* @} */

/*! @name PORTD0 (number 127), unused_0
  @{ */
#define BOARD_INITPINS_unused_0_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_unused_0_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_unused_0_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                           /* @} */

/*! @name PORTD6 (number 133), BUTTON
  @{ */
#define BOARD_INITPINS_BUTTON_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_BUTTON_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_BUTTON_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                         /* @} */

/*! @name PORTD7 (number 136), RELAY
  @{ */
#define BOARD_INITPINS_RELAY_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_RELAY_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_RELAY_PIN 7U     /*!<@brief PORTD pin index: 7 */
                                        /* @} */

/*! @name PORTD12 (number 141), LED_STATUS_G
  @{ */
#define BOARD_INITPINS_LED_STATUS_G_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_STATUS_G_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_STATUS_G_PIN 12U    /*!<@brief PORTD pin index: 12 */
                                               /* @} */

/*! @name PORTD13 (number 142), LED_STATUS_R
  @{ */
#define BOARD_INITPINS_LED_STATUS_R_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_STATUS_R_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_STATUS_R_PIN 13U    /*!<@brief PORTD pin index: 13 */
                                               /* @} */

/*! @name PORTD14 (number 143), LED_RS485
  @{ */
#define BOARD_INITPINS_LED_RS485_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_RS485_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_RS485_PIN 14U    /*!<@brief PORTD pin index: 14 */
                                            /* @} */

/*! @name PORTD15 (number 144), LED_SENSORS
  @{ */
#define BOARD_INITPINS_LED_SENSORS_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED_SENSORS_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED_SENSORS_PIN 15U    /*!<@brief PORTD pin index: 15 */
                                              /* @} */

/*! @name PORTC18 (number 125), 485_RE_2
  @{ */
#define BOARD_INITPINS_RS485_RE_2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_RS485_RE_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_RS485_RE_2_PIN 18U    /*!<@brief PORTC pin index: 18 */
                                             /* @} */

/*! @name PORTC19 (number 126), 485_DE_2
  @{ */
#define BOARD_INITPINS_RS485_DE_2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_RS485_DE_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_RS485_DE_2_PIN 19U    /*!<@brief PORTC pin index: 19 */
                                             /* @} */

/*! @name PORTB4 (number 85), 485_RE_1
  @{ */
#define BOARD_INITPINS_RS485_RE_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_RS485_RE_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RS485_RE_1_PIN 4U     /*!<@brief PORTB pin index: 4 */
                                             /* @} */

/*! @name PORTB5 (number 86), 485_DE_1
  @{ */
#define BOARD_INITPINS_RS485_DE_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_RS485_DE_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_RS485_DE_1_PIN 5U     /*!<@brief PORTB pin index: 5 */
                                             /* @} */

/*! @name PORTA4 (number 54), ETH_PHY_RESET
  @{ */
#define BOARD_INITPINS_ETH_PHY_RESET_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_ETH_PHY_RESET_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_ETH_PHY_RESET_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                                /* @} */

/*! @name PORTA6 (number 58), OPTO_INP_0
  @{ */
#define BOARD_INITPINS_OPTO_INP_0_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OPTO_INP_0_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OPTO_INP_0_PIN 6U     /*!<@brief PORTA pin index: 6 */
                                             /* @} */

/*! @name PORTA7 (number 59), OPTO_INP_1
  @{ */
#define BOARD_INITPINS_OPTO_INP_1_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OPTO_INP_1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OPTO_INP_1_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                             /* @} */

/*! @name PORTA8 (number 60), OPTO_INP_2
  @{ */
#define BOARD_INITPINS_OPTO_INP_2_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OPTO_INP_2_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OPTO_INP_2_PIN 8U     /*!<@brief PORTA pin index: 8 */
                                             /* @} */

/*! @name PORTA28 (number 79), unused_1
  @{ */
#define BOARD_INITPINS_unused_1_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_unused_1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_unused_1_PIN 28U    /*!<@brief PORTA pin index: 28 */
                                           /* @} */

/*! @name PORTC3 (number 106), SDHC_CD
  @{ */
#define BOARD_INITPINS_SDHC_CD_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SDHC_CD_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SDHC_CD_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                          /* @} */

/*
 * Application API
 */
#define HBUS232_DTR_OUT_PORT		PORTAN
#define HBUS232_DTR_OUT_PIN			5

#define PIGGYBACK232_IN_PORT		PORTQS
#define PIGGYBACK232_IN_PIN			6


typedef enum
{
	pbsYZ_FULL_DUP_485,				//full duplex available -> no piggy-232
	pbsYZ_FULL_DUP_232,
} EPiggyBackState;

void SetDtrState(int state);
EPiggyBackState GetPiggyBackState(void);

/*!
 * @brief Calls initialization functions.
 *
 */
void NutBoardInit(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void NutBoardInitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
